spring.application.name=kafka
management.endpoints.web.exposure.include=*
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=exchange-rate-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.topic=exchange-rates

exchange.api.url=https://api.exchangerate-api.com/v4/latest/USD

exchange.fetch.interval=30000
spring.elasticsearch.rest.sniffer.interval=0
spring.data.elasticsearch.repositories.enabled=false
spring.elasticsearch.compatibility-mode=true
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.index=exchange-rates